proyecto_T1/t1_project/comments/urls.py
from django.urls import path
from . import views


app_name = 'comments'
urlpatterns = [
    # ex: /pollss/
    path('', views.commenter, name='commenter'),
    path('comment/', views.comment, name='comment'),
    path('log/', views.log, name = 'log')
]

proyecto_T1/t1_project/t1_project/urls.py
from django.contrib import admin
from django.urls import path, include
from comments import views

urlpatterns = [
    path('', views.commenter),
    path('admin/', admin.site.urls),
    path('comments/', include('comments.urls'))
]

proyecto_T1/t1_project/comments/models.py
import datetime

from django.db import models

class Comment(models.Model):
    comment_text = models.CharField(max_length=500)
    time_sent = models.DateTimeField('date published')
    sender_ip = models.CharField(max_length=100)

    def __str__(self):
        return "Q: " + self.comment_text

proyecto_T1/t1_project/comments/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse

from .models import Comment
# Create your views here.

def commenter(request):
    return render(request, 'comments/commenter.html')

def comment(request):
    text = request.POST['commentText']
    if text == '':
        text = "///empty_commment///"
    comment = Comment(comment_text=text,
                      sender_ip=request.META['REMOTE_ADDR'],
                      time_sent=timezone.now())
    comment.save()
    return HttpResponseRedirect(reverse('comments:log'))

def log(request):
    latest_comments_list = Comment.objects.order_by('-time_sent')[:10]
    context = {'latest_comments_list': latest_comments_list}
    return render(request, 'comments/log.html', context)

proyecto_T1/t1_project/comments/templates/comments/commenter.html
<h1>Please enter your comment</h1>


<form action="{% url 'comments:comment'%}" method="post">
{% csrf_token %}
<textarea name="commentText" id="commentText" cols="40" rows="5"></textarea>
<input type="submit" value="Post comment">
</form>

proyecto_T1/t1_project/comments/templates/comments/log.html
<h1>Comentarios</h1>

{% if latest_comments_list %}
    <table style="width:100%">
      <tr>
        <th>Comment</th>
        <th>Sender ip</th>
        <th>Timestamp</th>
      </tr>
    {% for comment in latest_comments_list %}
        <tr>
          <td>{{comment.comment_text}}</td>
          <td>{{comment.sender_ip}}</td>
          <td>{{comment.time_sent}}</td>
        </tr>
    {% endfor %}
  </table>
{% else %}
    <p>No comments are available.</p>
{% endif %}

<a href="{% url 'comments:commenter' %}">Comment again</a>